version: "3.8"
services:
  web:
    build: .
    ports:
      - "3002:3002"
  mysql:
    container_name: db
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: serverena
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
